### PR TITLE
Added greyhole support

### PR DESCRIPTION
**Pull request by jancoow**

### CODE REVIEW

**Comment by Mastermindzh** [comment]
### Pull request denied for now

**Reason:** _App doesn't run anymore, probably hasn't gone through the testing stage either._

Upon visiting any URL the app now throws an "AssertionError" because from line 82 you use the same function name "get_disk_info()" for all functions. 

**Resolution:** _Rename functions and give them an appropriate name._

**Comment by jancoow** [comment]
Fixed now.

**Review by Mastermindzh — CHANGES_REQUESTED** [review]
Well done @jancoow, code looks clean and runs without issues! Before we merge however I would like to ask you to encapsulate all bash code in functions as per our agreements. This also still applies to the /DISK folder :)

**Comment by jancoow** [comment]
@Mastermindzh Updated greyhole & diskinfo.

**Pull request merged**
